### ISSUE TITLE
Inserting vectors does not work with Psycopg3

### ISSUE THREAD

**Issue by Andrea-Oliveri** [tensorchord/pgvecto.rs-py#16]
Good morning,
thank you for providing the PGVecto.rs extension and this package.
Unfortunately, I have been unable to make it work using Python + Psycopg3 to insert new values into the database.

Please find underneath the steps to, hopefully, replicate my issue:

1. Create a locally-hosted Postgres database with PGVecto.rs extension installed:
```bash
docker run --name pgvecto-rs-test -e POSTGRES_PASSWORD=pwd -p 5555:5432 -d tensorchord/pgvecto-rs:pg16-v0.2.1
```

2. Create a conda environment with the minimal number of packages:
```bash
conda create -n pgvecto_rs python
conda activate pgvecto_rs
pip install psycopg "pgvecto_rs[psycopg3]"
```
this step resulted in the following environment for me on Windows:
```bash
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h2bbff1b_6
ca-certificates           2024.9.24            haa95532_0
expat                     2.6.3                h5da7b33_0
libffi                    3.4.4                hd77b12b_1
numpy                     2.1.2                    pypi_0    pypi
openssl                   3.0.15               h827c3e9_0
pgvecto-rs                0.2.2                    pypi_0    pypi
pip                       24.2            py312haa95532_0
psycopg                   3.2.3                    pypi_0    pypi
psycopg-binary            3.2.3                    pypi_0    pypi
python                    3.12.7               h14ffc60_0
setuptools                75.1.0          py312haa95532_0
sqlite                    3.45.3               h2bbff1b_0
tk                        8.6.14               h0416ee5_0
toml                      0.10.2                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.2                   pypi_0    pypi
vc                        14.40                h2eaa2aa_1
vs2015_runtime            14.40.33807          h98bb1dd_1
wheel                     0.44.0          py312haa95532_0
xz                        5.4.6                h8cc25b3_1
zlib                      1.2.13               h8cc25b3_1
```

3. Run the following Python script:
```python
import psycopg
from pgvecto_rs.psycopg import register_vector

con = psycopg.connect('host=localhost port=5555 password=pwd user=postgres')
con.execute("DROP EXTENSION IF EXISTS vectors;")
con.execute("CREATE EXTENSION vectors;")
con.commit()

register_vector(con)

con.execute("CREATE TABLE items (id bigserial PRIMARY KEY, embedding vector(3) NOT NULL)")
con.commit()

# Note: everything works this far. The exception is raised by the next line:
con.execute('insert into items (embedding) values (%s)', ([1, 2, 3], ))
```

This fails with the following exception:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\andre\miniconda3\envs\pgvecto_rs\Lib\site-packages\psycopg\connection.py", line 251, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedFunction: no binary input function available for type vector
CONTEXT:  unnamed portal parameter $1
```

Of note:
- The above procedure closely follows your recommendations on how to deploy and use both the extension and the package
- A similar setup with PGVector works without any issues
- The script fails regardless of the type provided for the vector element. Tried with list, tuple and numpy array

Thank you in advance for your help, and I remain at your disposal for any clarifications.

**Comment by kemingy** [comment]
You can try `tensorchord/pgvecto-rs:pg16-v0.3.0`, `pgvecto_rs==0.2.2` is for `pgvecto-rs:v0.3.0`.

**Comment by Andrea-Oliveri** [comment]
This worked, thank you!
